Source3: filter_macro_for_special_modules
%define __perl_requires %{SOURCE3}
Summary: Gearman-XS Perl module
Name: perl-Gearman-XS
Version: 0.12
Release: 1
Packager: cpanpackager
License: GPL or Artistic
Group: Development/Libraries
URL: http://search.cpan.org/dist/Gearman-XS/
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildRequires: perl(Test::More)
BuildRequires: perl(ExtUtils::MakeMaker) >= 6.42
BuildRequires: perl(Storable)
Source0: Gearman::XS-0.12.tar.gz

%description
%{summary}.

%prep
%setup -q -n Gearman-XS-%{version}

%build
CFLAGS="$RPM_OPT_FLAGS" %{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags} OPTIMIZE="$RPM_OPT_FLAGS"

%check
make test

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT
if [ -d $RPM_BUILD_ROOT$RPM_BUILD_ROOT ]; then mv $RPM_BUILD_ROOT$RPM_BUILD_ROOT/* $RPM_BUILD_ROOT; fi

find $RPM_BUILD_ROOT -type f -a \( -name perllocal.pod -o -name .packlist \
  -o \( -name '*.bs' -a -empty \) \) -exec rm -f {} ';'
find $RPM_BUILD_ROOT -type d -depth -exec rmdir {} 2>/dev/null ';'
chmod -R u+w $RPM_BUILD_ROOT/*

for brp in %{_prefix}/lib/rpm/%{_build_vendor}/brp-compress \
  %{_prefix}/lib/rpm/brp-compress
do
  [ -x $brp ] && $brp && break
done


find $RPM_BUILD_ROOT -type f \
| sed "s@^$RPM_BUILD_ROOT@@g" \
> %{name}-%{version}-%{release}-filelist

eval `%{__perl} -V:archname -V:installsitelib -V:installvendorlib -V:installprivlib`
for d in $installsitelib $installvendorlib $installprivlib; do
  [ -z "$d" -o "$d" = "UNKNOWN" -o ! -d "$RPM_BUILD_ROOT$d" ] && continue
  find $RPM_BUILD_ROOT$d/* -type d \
  | grep -v "/$archname\(/auto\)\?$" \
  | sed "s@^$RPM_BUILD_ROOT@%dir @g" \
  >> %{name}-%{version}-%{release}-filelist
done

if [ "$(cat %{name}-%{version}-%{release}-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%clean
rm -rf $RPM_BUILD_ROOT

%files -f %{name}-%{version}-%{release}-filelist
%defattr(-,root,root,-)
%doc Changes README

%changelog
* Mon Jan 23 2012 root <root@redhat.com> - 0.12-1
- Specfile autogenerated with command '/usr/bin/cpan-packager /tmp/_qpf6VZuuf/Gearman::XS-0.12.tar.gz'

